name: Check korean grammar on Pull Request

# 댓글이 아니라, PR이 새로 열리거나 코드가 추가로 푸시될 때 자동으로 실행됩니다.
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  grammar_check:
    runs-on: ubuntu-latest

    steps:
      - name: "맞춤법 검사 봇 실행"
        uses: unoung/korean-grammar-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
